# Generated by Django 4.1.7 on 2023-03-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_livro_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='livraria.autor'),
        ),
    ]
