# Generated by Django 4.1.7 on 2023-03-24 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0006_alter_livro_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, validators=[django.core.validators.RegexValidator('^\\d*\\.?\\d+$', 'Apenas números são permitidos.')]),
        ),
    ]
